on: 
  release:
    types:
      - released

name: release-announcement.yaml

jobs:
  release-annoucement:
    runs-on: ubuntu-latest
    name: Sends custom message
    steps:
      - name: Dump release event content
        if: false
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Send a message on discord
        uses: MineBartekSA/discord-webhook@v2
        env:
          AUTHOR_ICON_URL: "${{ github.event.release.author.avatar_url }}"
          AUTHOR_NAME: "${{ github.event.release.author.login }}"
          CHANGELOG_URL: "${{ github.event.release.html_url }}"
          RELEASE_DATE: "${{ github.event.release.created_at }}"
          RELEASE_VERSION: "${{ github.event.release.tag_name }}"
          REPOSITORY_DESCRIPTION: "Generate diagrams from textual description"
          REPOSITORY_ID: "evantill/plantuml-cheerpj"
          REPOSITORY_NAME: "plantuml-cheerpj"
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEV_RELEASE }}
          username: Plantuml
          avatar_url: https://avatars.githubusercontent.com/plantuml
          content: Thank you to all who have contributed in this great work.
          component: |
            - type: 1
              components:
                - style: 5
                  type: 2
                  label: ChangeLog
                  url: ${{ env.CHANGELOG_URL }}
          embed: |
            title: "\U0001F389 ${{ env.REPOSITORY_NAME }} version ${{ env.RELEASE_VERSION }} is published ! \U0001F389"
            color: 0x892038
            description: "${{ env.REPOSITORY_DESCRIPTION }}"
            url: ${{ env.CHANGELOG_URL }}
            image:
              url: https://miro.medium.com/v2/1*8-G_ojoQPPmnG8ig1RiZfg.png
            fields:
              - name: Project
                value: ${{ env.REPOSITORY_ID }}
              - name: Version
                value: ${{ env.RELEASE_VERSION }}
              - name: Release date
                value: "${{ env.RELEASE_DATE }}"
            timestamp: "${{ env.RELEASE_DATE }}"
            thumbnail:
              url: https://davidfpresents.com/wp-content/uploads/2018/02/shadok.jpg
            footer:
              text: ${{ env.AUTHOR_NAME }}
              icon_url: ${{ env.AUTHOR_ICON_URL }}
