on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Automation

jobs:
  release-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_BOT_TOKEN }}
          release-type: simple

