name: Release Announcement

on: 
  release:
    types:
      - released

jobs:
  release-notification:
    runs-on: ubuntu-latest
    name: Sends custom message
    steps:
      - name: Dump release event content
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Sending message
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_RELEASE_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_RELEASE_TOKEN }}