name: WIP Discord

on:
  workflow_dispatch:

jobs:
  wip-discord:
    name: Send Discord message
    runs-on: ubuntu-latest
    steps:

 

      # - name: define discord message
      #   id: discord-message
      #   env:
      #     DISCORD_MESSAGE: |
      #       channel_id: context.params.event.channel_id
      #       content: ''
      #       tts: false
      #       components:
      #       - type: 1
      #         components:
      #         - style: 5
      #           label: Release Note
      #           url: https://github.com/evantill/plantuml-cheerpj/blob/v1.2.0-alpha/CHANGELOG.md
      #           disabled: false
      #           type: 2
      #       embeds:
      #       - type: rich
      #         title: plantuml-chieddkdkd Release 1.2.3
      #         description: ''
      #         color: '0xF6BC55'
      #         fields:
      #         - name: Repository
      #           value: evantill/plantuml-chieddkdkd
      #           inline: true
      #         - name: Version
      #           value: 1.2.3.4
      #           inline: true
      #         thumbnail:
      #           url: https://avatars.githubusercontent.com/evantill
      #           height: 0
      #           width: 0
      #         author:
      #           name: evantill
      #           url: https://github.com/evantill
      #           icon_url: https://avatars.githubusercontent.com/evantill
      #         footer:
      #           text: 21/07/2023
      #         url: https://github.com/evantill/plantuml-cheerpj/releases/tag/untagged-213445f7e7a8e3b5f93d
      #   run: |
      #     #yaml to json
      #     DISCORD_MESSAGE=$(echo "$DISCORD_MESSAGE" | yq -o=json . -I 0 -M -)
      #     echo "DISCORD_MESSAGE=$DISCORD_MESSAGE" >> $GITHUB_OUTPUT

      # - name: test message
      #   env:
      #     SOME_PART: ${{ toJson(fromJSON(steps.discord-message.outputs.DISCORD_MESSAGE).embeds) }}
      #   run: |
      #     echo "SOME_PART=$SOME_PART"

      - name: Send a message with a component using YAML
        uses: MineBartekSA/discord-webhook@v2
        env:
          CHANGELOG_URL: "https://github.com/evantill/plantuml-cheerpj/releases/tag/v1.2.0-alpha"
          REPOSITORY_NAME: "plantuml-cheerpj"
          REPOSITORY_ID: "evantill/plantuml-cheerpj"
          REPOSITORY_DESCRIPTION: "Generate diagrams from textual description"
          RELEASE_DATE: "2015-12-31T12:00:00.000Z"
          RELEASE_VERSION: "v1.2.3.4"
          AUTHOR_NAME: "evantill"
          AUTHOR_URL: "https://avatars.githubusercontent.com/u/609288?v=4"
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_TEST_URL }}
          username: Plantuml
          avatar_url: https://avatars.githubusercontent.com/plantuml
          content: Thank you to all who have contributed in this great work.
          component: |
            - type: 1
              components:
                - style: 5
                  type: 2
                  label: ChangeLog
                  url: ${{ env.CHANGELOG_URL }}
          embed: |
            title: "\U0001F389 ${{ env.REPOSITORY_NAME }} version ${{ env.RELEASE_VERSION }} is published ! \U0001F389"
            color: 0x892038
            description: "${{ env.REPOSITORY_DESCRIPTION }}"
            url: ${{ env.CHANGELOG_URL }}
            image:
              url: https://miro.medium.com/v2/1*8-G_ojoQPPmnG8ig1RiZfg.png
            fields:
              - name: Project
                value: ${{ env.REPOSITORY_ID }}
              - name: Version
                value: ${{ env.RELEASE_VERSION }}
              - name: Release date
                value: "${{ env.RELEASE_DATE }}"
            timestamp: "${{ env.RELEASE_DATE }}"
            thumbnail:
              url: https://davidfpresents.com/wp-content/uploads/2018/02/shadok.jpg
            footer:
              text: ${{ env.AUTHOR_NAME }}
              icon_url: ${{ env.AUTHOR_URL }}

      # - name: Send discord message
      #   uses: Ilshidur/action-discord@0.3.2
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #     EVENT_PAYLOAD: ${{ toJson(github.event) }}
      #     DISCORD_EMBEDS: ${{ toJson(fromJSON(steps.discord-message.outputs.DISCORD_MESSAGE).embeds) }}
      #   with:
      #     args: "The project ${{ env.EVENT_PAYLOAD.repository.full_name }} has been deployed."